### ISSUE TITLE
Error when running second controller.

### ISSUE THREAD

**Issue by sw1044122811** [Junzeng-x14/Quadrotor_Suspended#2]

**Comment by junzengx14** [comment]
Could you elaborate more details about it?

**Comment by sw1044122811** [comment]
Hi, when I run controller2, I directly modified Solving Dynamical Equations[t,x] in mian.m to control2, is it correct to run this way? And after doing so it suggests that the array index must be a positive integer or a logical value, and neither Ind nor J in the workspace can be calculated. Thanks for the answer.

**Comment by sw1044122811** [comment]
Hi, how do I run it with controller 2?
